# Generated by Django 3.2 on 2024-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')])),
            ],
        ),
    ]
